repos:
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          #entry: pylint error.py
          entry: uptime
          language: system
          always_run: true
          pass_filenames: false
