version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      # Password for root access
      MARIADB_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
